export interface Channel {
  name: string;
  countryCode: string; // ISO 3166-1 alpha-2
  countryName: string;
  quality: '4K 60FPS' | '4K UHD' | 'FHD' | 'HD';
  category: 'Sports' | 'Entertainment' | 'Cinema' | 'News' | 'Documentary' | 'Kids';
  bitrate: string;
}

export interface CountryMeta {
  code: string;
  name: string;
  count: string;
}

export const WORLD_COUNTRIES: CountryMeta[] = [
  { code: 'US', name: 'United States', count: '4,800+' },
  { code: 'GB', name: 'United Kingdom', count: '2,200+' },
  { code: 'CA', name: 'Canada', count: '1,400+' },
  { code: 'FR', name: 'France', count: '1,800+' },
  { code: 'DE', name: 'Germany', count: '1,600+' },
  { code: 'ES', name: 'Spain', count: '1,300+' },
  { code: 'IT', name: 'Italy', count: '1,500+' },
  { code: 'PT', name: 'Portugal', count: '750+' },
  { code: 'NL', name: 'Netherlands', count: '820+' },
  { code: 'MA', name: 'Morocco', count: '450+' },
  { code: 'SA', name: 'Saudi Arabia', count: '980+' },
  { code: 'AE', name: 'UAE', count: '620+' },
  { code: 'EG', name: 'Egypt', count: '740+' },
  { code: 'BR', name: 'Brazil', count: '1,900+' },
  { code: 'MX', name: 'Mexico', count: '1,100+' },
  { code: 'AU', name: 'Australia', count: '890+' },
  { code: 'IN', name: 'India', count: '2,100+' },
  { code: 'TR', name: 'Turkey', count: '1,050+' },
  { code: 'SE', name: 'Sweden', count: '610+' },
  { code: 'NO', name: 'Norway', count: '540+' },
  { code: 'BE', name: 'Belgium', count: '680+' },
  { code: 'CH', name: 'Switzerland', count: '590+' },
  { code: 'PL', name: 'Poland', count: '780+' },
  { code: 'ZA', name: 'South Africa', count: '520+' },
];

export interface ChannelCategoryData {
  title: string;
  slug: string;
  badge: string;
  description: string;
  channels: Channel[];
}

export const CHANNELS_DATA: Record<string, ChannelCategoryData> = {
  'live-sports-hd': {
    title: 'Worldwide Live Sports & PPV Stadium Feeds',
    slug: 'live-sports-hd',
    badge: 'Live Sports 60 FPS',
    description: 'Direct satellite and fiber feeds for Premier League, Champions League, La Liga, Serie A, UFC PPVs, Formula 1, and NBA.',
    channels: [
      { name: 'Sky Sports Main Event', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K 60FPS', category: 'Sports', bitrate: '18 Mbps' },
      { name: 'Sky Sports Premier League', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K 60FPS', category: 'Sports', bitrate: '18 Mbps' },
      { name: 'TNT Sports 1 Ultimate', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'TNT Sports 2 HD', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Sports', bitrate: '12 Mbps' },
      { name: 'ESPN USA HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'ESPN 2 USA', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'Fox Sports 1 (FS1)', countryCode: 'US', countryName: 'United States', quality: '4K 60FPS', category: 'Sports', bitrate: '20 Mbps' },
      { name: 'NBC Sports Network', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Sports', bitrate: '12 Mbps' },
      { name: 'beIN Sports 1 Premium English', countryCode: 'QA', countryName: 'Qatar', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'beIN Sports 2 AFC', countryCode: 'QA', countryName: 'Qatar', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'Canal+ Sport France', countryCode: 'FR', countryName: 'France', quality: '4K 60FPS', category: 'Sports', bitrate: '20 Mbps' },
      { name: 'RMC Sport 1', countryCode: 'FR', countryName: 'France', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'DAZN 1 Bar HD', countryCode: 'DE', countryName: 'Germany', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'Sky Sport Bundesliga 1', countryCode: 'DE', countryName: 'Germany', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'Movistar LaLiga 4K', countryCode: 'ES', countryName: 'Spain', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'Movistar Liga de Campeones', countryCode: 'ES', countryName: 'Spain', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'Sky Sport Serie A 4K', countryCode: 'IT', countryName: 'Italy', quality: '4K 60FPS', category: 'Sports', bitrate: '20 Mbps' },
      { name: 'Sky Sport F1 Italia', countryCode: 'IT', countryName: 'Italy', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'Sport TV 1 Portugal', countryCode: 'PT', countryName: 'Portugal', quality: 'FHD', category: 'Sports', bitrate: '12 Mbps' },
      { name: 'Ziggo Sport Select 4K', countryCode: 'NL', countryName: 'Netherlands', quality: '4K 60FPS', category: 'Sports', bitrate: '20 Mbps' },
      { name: 'Arryadia TNT HD', countryCode: 'MA', countryName: 'Morocco', quality: 'FHD', category: 'Sports', bitrate: '10 Mbps' },
      { name: 'SSC Sports 1 HD (Saudi Pro)', countryCode: 'SA', countryName: 'Saudi Arabia', quality: '4K 60FPS', category: 'Sports', bitrate: '20 Mbps' },
      { name: 'AD Sports Premium 1', countryCode: 'AE', countryName: 'UAE', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'ON Time Sports 1', countryCode: 'EG', countryName: 'Egypt', quality: 'FHD', category: 'Sports', bitrate: '12 Mbps' },
      { name: 'SporTV Brazil 4K', countryCode: 'BR', countryName: 'Brazil', quality: '4K 60FPS', category: 'Sports', bitrate: '20 Mbps' },
      { name: 'TUDN Mexico HD', countryCode: 'MX', countryName: 'Mexico', quality: 'FHD', category: 'Sports', bitrate: '12 Mbps' },
      { name: 'TSN 1 Canada 4K', countryCode: 'CA', countryName: 'Canada', quality: '4K 60FPS', category: 'Sports', bitrate: '20 Mbps' },
      { name: 'Sportsnet ONE Canada', countryCode: 'CA', countryName: 'Canada', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'Optus Sport 1', countryCode: 'AU', countryName: 'Australia', quality: 'FHD', category: 'Sports', bitrate: '14 Mbps' },
      { name: 'Star Sports 1 HD Select', countryCode: 'IN', countryName: 'India', quality: 'FHD', category: 'Sports', bitrate: '12 Mbps' },
      { name: 'SuperSport Premier League', countryCode: 'ZA', countryName: 'South Africa', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'UFC Main Card PPV Live', countryCode: 'US', countryName: 'United States', quality: '4K 60FPS', category: 'Sports', bitrate: '24 Mbps' },
    ],
  },
  'us-uk-entertainment': {
    title: 'US, UK & English Prime Entertainment',
    slug: 'us-uk-entertainment',
    badge: 'Premium VOD & Drama',
    description: 'Major flagship broadcast networks, private drama studios, and 24/7 uncompressed sitcom channels.',
    channels: [
      { name: 'HBO East 4K', countryCode: 'US', countryName: 'United States', quality: '4K UHD', category: 'Entertainment', bitrate: '20 Mbps' },
      { name: 'HBO 2 USA', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Showtime East', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Starz Cinema HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'AMC Premiere HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'FX Networks East', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'USA Network 4K', countryCode: 'US', countryName: 'United States', quality: '4K UHD', category: 'Entertainment', bitrate: '18 Mbps' },
      { name: 'Discovery Channel 4K', countryCode: 'US', countryName: 'United States', quality: '4K UHD', category: 'Documentary', bitrate: '20 Mbps' },
      { name: 'National Geographic Wild', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Documentary', bitrate: '14 Mbps' },
      { name: 'History Channel HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Documentary', bitrate: '12 Mbps' },
      { name: 'Comedy Central US', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Paramount Network', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Bravo East HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '10 Mbps' },
      { name: 'ABC East 4K', countryCode: 'US', countryName: 'United States', quality: '4K UHD', category: 'Entertainment', bitrate: '18 Mbps' },
      { name: 'NBC East FHD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'CBS East FHD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'FOX East 4K', countryCode: 'US', countryName: 'United States', quality: '4K UHD', category: 'Entertainment', bitrate: '18 Mbps' },
      { name: 'BBC One London 4K', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K UHD', category: 'Entertainment', bitrate: '20 Mbps' },
      { name: 'BBC Two HD', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'ITV 1 HD London', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Channel 4 HD UK', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Sky Atlantic 4K', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K UHD', category: 'Entertainment', bitrate: '22 Mbps' },
      { name: 'Sky Max HD', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Entertainment', bitrate: '14 Mbps' },
      { name: 'Sky Showcase HD', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Entertainment', bitrate: '14 Mbps' },
      { name: 'Gold Comedy UK', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Entertainment', bitrate: '10 Mbps' },
      { name: 'Alibi Channel UK', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Entertainment', bitrate: '10 Mbps' },
      { name: 'CBC Television Canada', countryCode: 'CA', countryName: 'Canada', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'CTV HD Toronto', countryCode: 'CA', countryName: 'Canada', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Channel 7 Sydney', countryCode: 'AU', countryName: 'Australia', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Channel 9 Melbourne', countryCode: 'AU', countryName: 'Australia', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Disney Channel US HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Kids', bitrate: '10 Mbps' },
      { name: 'Cartoon Network UK', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Kids', bitrate: '10 Mbps' },
    ],
  },
  'international-feeds': {
    title: 'International European, Arab & Worldwide Feeds',
    slug: 'international-feeds',
    badge: '100+ Nations Covered',
    description: 'Regional flagship state & commercial networks across Europe, MENA, South America, and Asia.',
    channels: [
      { name: 'TF1 France 4K', countryCode: 'FR', countryName: 'France', quality: '4K UHD', category: 'Entertainment', bitrate: '20 Mbps' },
      { name: 'France 2 HD', countryCode: 'FR', countryName: 'France', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'M6 France HD', countryCode: 'FR', countryName: 'France', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Canal+ France 4K', countryCode: 'FR', countryName: 'France', quality: '4K UHD', category: 'Entertainment', bitrate: '22 Mbps' },
      { name: 'Das Erste (ARD) HD', countryCode: 'DE', countryName: 'Germany', quality: 'FHD', category: 'Entertainment', bitrate: '14 Mbps' },
      { name: 'ZDF HD Germany', countryCode: 'DE', countryName: 'Germany', quality: 'FHD', category: 'Entertainment', bitrate: '14 Mbps' },
      { name: 'RTL Television HD', countryCode: 'DE', countryName: 'Germany', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'ProSieben HD', countryCode: 'DE', countryName: 'Germany', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Rai 1 4K Italia', countryCode: 'IT', countryName: 'Italy', quality: '4K UHD', category: 'Entertainment', bitrate: '20 Mbps' },
      { name: 'Rai 2 HD', countryCode: 'IT', countryName: 'Italy', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Canale 5 HD', countryCode: 'IT', countryName: 'Italy', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Italia 1 HD', countryCode: 'IT', countryName: 'Italy', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'La 1 TVE 4K', countryCode: 'ES', countryName: 'Spain', quality: '4K UHD', category: 'Entertainment', bitrate: '20 Mbps' },
      { name: 'Antena 3 Spain', countryCode: 'ES', countryName: 'Spain', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Telecinco HD', countryCode: 'ES', countryName: 'Spain', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'RTP 1 Portugal', countryCode: 'PT', countryName: 'Portugal', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'SIC Portugal HD', countryCode: 'PT', countryName: 'Portugal', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'NPO 1 4K', countryCode: 'NL', countryName: 'Netherlands', quality: '4K UHD', category: 'Entertainment', bitrate: '18 Mbps' },
      { name: 'RTL 4 Netherlands', countryCode: 'NL', countryName: 'Netherlands', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Al Aoula Inter HD', countryCode: 'MA', countryName: 'Morocco', quality: 'FHD', category: 'Entertainment', bitrate: '10 Mbps' },
      { name: '2M Maroc National', countryCode: 'MA', countryName: 'Morocco', quality: 'FHD', category: 'Entertainment', bitrate: '10 Mbps' },
      { name: 'MBC 1 HD Global', countryCode: 'SA', countryName: 'Saudi Arabia', quality: 'FHD', category: 'Entertainment', bitrate: '14 Mbps' },
      { name: 'MBC Masr HD', countryCode: 'EG', countryName: 'Egypt', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Dubai TV 4K', countryCode: 'AE', countryName: 'UAE', quality: '4K UHD', category: 'Entertainment', bitrate: '18 Mbps' },
      { name: 'TV Globo 4K', countryCode: 'BR', countryName: 'Brazil', quality: '4K UHD', category: 'Entertainment', bitrate: '20 Mbps' },
      { name: 'SBT Brazil HD', countryCode: 'BR', countryName: 'Brazil', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Las Estrellas 4K', countryCode: 'MX', countryName: 'Mexico', quality: '4K UHD', category: 'Entertainment', bitrate: '18 Mbps' },
      { name: 'Azteca Uno HD', countryCode: 'MX', countryName: 'Mexico', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'TRT 1 4K Turkey', countryCode: 'TR', countryName: 'Turkey', quality: '4K UHD', category: 'Entertainment', bitrate: '18 Mbps' },
      { name: 'SVT 1 HD Sweden', countryCode: 'SE', countryName: 'Sweden', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Zee TV HD India', countryCode: 'IN', countryName: 'India', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
      { name: 'Star Plus India HD', countryCode: 'IN', countryName: 'India', quality: 'FHD', category: 'Entertainment', bitrate: '12 Mbps' },
    ],
  },
  '24-7-news-feeds': {
    title: '24/7 Global Breaking News & Business Feeds',
    slug: '24-7-news-feeds',
    badge: 'Live Wire 24/7',
    description: 'Instant global perspectives, financial exchange streams, and round-the-clock international press bureaus.',
    channels: [
      { name: 'BBC News Channel HD', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Sky News UK HD', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'CNN International 4K', countryCode: 'US', countryName: 'United States', quality: '4K UHD', category: 'News', bitrate: '18 Mbps' },
      { name: 'CNN US Domestic', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Fox News Channel HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'MSNBC Live HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'CNBC US Live', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Bloomberg Global HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'News', bitrate: '14 Mbps' },
      { name: 'Al Jazeera English HD', countryCode: 'QA', countryName: 'Qatar', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Al Jazeera Arabic HD', countryCode: 'QA', countryName: 'Qatar', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'France 24 English', countryCode: 'FR', countryName: 'France', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'France 24 Français', countryCode: 'FR', countryName: 'France', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'BFM TV France HD', countryCode: 'FR', countryName: 'France', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'DW News Global HD', countryCode: 'DE', countryName: 'Germany', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'n-tv Germany HD', countryCode: 'DE', countryName: 'Germany', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'Sky TG24 Italia', countryCode: 'IT', countryName: 'Italy', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Canal 24 Horas Spain', countryCode: 'ES', countryName: 'Spain', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'Euronews English', countryCode: 'FR', countryName: 'France', quality: 'HD', category: 'News', bitrate: '8 Mbps' },
      { name: 'Al Arabiya News HD', countryCode: 'AE', countryName: 'UAE', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Sky News Arabia', countryCode: 'AE', countryName: 'UAE', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Al Hadath News', countryCode: 'SA', countryName: 'Saudi Arabia', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Medi 1 TV Afrique', countryCode: 'MA', countryName: 'Morocco', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'CBC News Network', countryCode: 'CA', countryName: 'Canada', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'ABC News Australia', countryCode: 'AU', countryName: 'Australia', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'NHK World Japan HD', countryCode: 'JP', countryName: 'Japan', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'WION News India HD', countryCode: 'IN', countryName: 'India', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'NDTV 24x7 India', countryCode: 'IN', countryName: 'India', quality: 'HD', category: 'News', bitrate: '8 Mbps' },
      { name: 'GloboNews Brazil', countryCode: 'BR', countryName: 'Brazil', quality: 'FHD', category: 'News', bitrate: '12 Mbps' },
      { name: 'Foro TV Mexico', countryCode: 'MX', countryName: 'Mexico', quality: 'FHD', category: 'News', bitrate: '10 Mbps' },
      { name: 'C-SPAN 1 USA', countryCode: 'US', countryName: 'United States', quality: 'HD', category: 'News', bitrate: '8 Mbps' },
    ],
  },
  'ppv-cinema-vod': {
    title: 'Pay-Per-View Stadiums & Worldwide 4K Cinema Vaults',
    slug: 'ppv-cinema-vod',
    badge: 'Exclusive Cinema 4K',
    description: 'Direct high-bitrate passes for Championship boxing, MMA title cards, and dedicated 24/7 movie screens without interruptions.',
    channels: [
      { name: 'Sky Cinema Premiere 4K', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K UHD', category: 'Cinema', bitrate: '22 Mbps' },
      { name: 'Sky Cinema Action HD', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Cinema', bitrate: '14 Mbps' },
      { name: 'Sky Cinema Sci-Fi & Horror', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Cinema', bitrate: '14 Mbps' },
      { name: 'Film4 HD UK', countryCode: 'GB', countryName: 'United Kingdom', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'HBO Signature HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Cinema', bitrate: '14 Mbps' },
      { name: 'HBO Comedy US', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'Starz Edge HD', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'Showtime Extreme US', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'Cinemax ActionMax', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'TCM Turner Classic Movies', countryCode: 'US', countryName: 'United States', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'Paramount+ Cinema Live 4K', countryCode: 'US', countryName: 'United States', quality: '4K UHD', category: 'Cinema', bitrate: '20 Mbps' },
      { name: 'Canal+ Cinema France 4K', countryCode: 'FR', countryName: 'France', quality: '4K UHD', category: 'Cinema', bitrate: '22 Mbps' },
      { name: 'Ciné+ Premier France', countryCode: 'FR', countryName: 'France', quality: 'FHD', category: 'Cinema', bitrate: '14 Mbps' },
      { name: 'Sky Cinema Uno 4K Italia', countryCode: 'IT', countryName: 'Italy', quality: '4K UHD', category: 'Cinema', bitrate: '20 Mbps' },
      { name: 'Sky Cinema Action Italia', countryCode: 'IT', countryName: 'Italy', quality: 'FHD', category: 'Cinema', bitrate: '14 Mbps' },
      { name: 'Movistar Estrenos 4K', countryCode: 'ES', countryName: 'Spain', quality: '4K UHD', category: 'Cinema', bitrate: '22 Mbps' },
      { name: 'Movistar Comedia HD', countryCode: 'ES', countryName: 'Spain', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'Sky Cinema Premieren 4K', countryCode: 'DE', countryName: 'Germany', quality: '4K UHD', category: 'Cinema', bitrate: '20 Mbps' },
      { name: 'Rotana Cinema HD', countryCode: 'EG', countryName: 'Egypt', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'Rotana Classic', countryCode: 'EG', countryName: 'Egypt', quality: 'HD', category: 'Cinema', bitrate: '10 Mbps' },
      { name: 'Telecine Premium Brazil', countryCode: 'BR', countryName: 'Brazil', quality: 'FHD', category: 'Cinema', bitrate: '14 Mbps' },
      { name: 'Telecine Action Brazil', countryCode: 'BR', countryName: 'Brazil', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'Cinecanal Mexico HD', countryCode: 'MX', countryName: 'Mexico', quality: 'FHD', category: 'Cinema', bitrate: '12 Mbps' },
      { name: 'UFC Main Card PPV Live', countryCode: 'US', countryName: 'United States', quality: '4K 60FPS', category: 'Sports', bitrate: '24 Mbps' },
      { name: 'UFC Prelims Live', countryCode: 'US', countryName: 'United States', quality: '4K 60FPS', category: 'Sports', bitrate: '18 Mbps' },
      { name: 'WWE Royal Rumble / WrestleMania', countryCode: 'US', countryName: 'United States', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'Boxing World Championship PPV', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K 60FPS', category: 'Sports', bitrate: '24 Mbps' },
      { name: 'DAZN PPV Events 4K', countryCode: 'US', countryName: 'United States', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'TNT Sports Box Office', countryCode: 'GB', countryName: 'United Kingdom', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
      { name: 'SuperSport Action PPV 4K', countryCode: 'ZA', countryName: 'South Africa', quality: '4K 60FPS', category: 'Sports', bitrate: '22 Mbps' },
    ],
  },
};